"""initial_models

Revision ID: 93327536220a
Revises: 
Create Date: 2026-06-14 16:52:38.838253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93327536220a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('idProd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cant', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('idProd')
    )
    op.create_table('sell',
    sa.Column('idSell', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cant', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idSell')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'vendedor', name='user_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entry',
    sa.Column('idEntry', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProd', sa.Integer(), nullable=False),
    sa.Column('cant', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['idProd'], ['product.idProd'], ),
    sa.PrimaryKeyConstraint('idEntry')
    )
    op.create_table('out',
    sa.Column('idOut', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProd', sa.Integer(), nullable=False),
    sa.Column('cant', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['idProd'], ['product.idProd'], ),
    sa.PrimaryKeyConstraint('idOut')
    )
    op.create_table('prod_sell',
    sa.Column('idProd', sa.Integer(), nullable=False),
    sa.Column('idSell', sa.Integer(), nullable=False),
    sa.Column('cant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProd'], ['product.idProd'], ),
    sa.ForeignKeyConstraint(['idSell'], ['sell.idSell'], ),
    sa.PrimaryKeyConstraint('idProd', 'idSell')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prod_sell')
    op.drop_table('out')
    op.drop_table('entry')
    op.drop_table('users')
    op.drop_table('sell')
    op.drop_table('product')
    # ### end Alembic commands ###
